title = 'configuration'

[simulation]
    jsbsim_dt_hz = 50  # JSBSim integration frequency in Herz
    agent_interaction_freq = 5 # Interaction Frequency in Herz
    path_jsbsim = '~/jsbsim' ### path to jsbsim folder

    [simulation.aircraft]
        jsbsim_id='c172p'
        flightgear_id='c172p'
        name='Cessna172P'
        cruise_speed_kts=120
    # Examples for a different aircraft:
    #[simulation.aircraft]
    #    jsbsim_id='a320'
    #    flightgear_id='A320'
    #    name='A320-211'
    #    cruise_speed_kts=490
    #[simulation.aircraft]
    #    jsbsim_id='f15'
    #    flightgear_id='f15'
    #    name='f15c'
    # cruise_speed_kts=220

    [simulation.initial_state]
        'ic/h-sl-ft' = 10000
        'ic/u-fps' = 120
        'ic/terrain-elevation-ft' = 0.00001
        'ic/psi-true-deg' = 270

    [simulation.start_conditions]
        'propulsion/engine/set-running' = 1

[flightgear]
    'running' = true
    'flightgear_time_factor' = 1
